wjctest.lo: /usr/local/src/php-7.1.0/ext/wjctest/wjctest.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/usr/local/src/php-7.1.0/ext/wjctest $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /usr/local/src/php-7.1.0/ext/wjctest/wjctest.c -o wjctest.lo 
$(phplibdir)/wjctest.la: ./wjctest.la
	$(LIBTOOL) --mode=install cp ./wjctest.la $(phplibdir)

./wjctest.la: $(shared_objects_wjctest) $(WJCTEST_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_wjctest) $(WJCTEST_SHARED_LIBADD)

